# Generated by Django 4.2.3 on 2023-07-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=10)),
                ('postion', models.CharField(max_length=100)),
            ],
        ),
    ]
